# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: NPM CI
on:
  push:
    branches:
      - '*' # matches every branch
      - '*/*' # matches every branch containing a single '/'
      - '!main' # main is handled in a separate workflow

jobs:
  verify-compile:
    name: Verify code and docs compile
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version:
          - 18.x

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run elm make
      run: |
        npx -y elm make --docs=docs.json
